'use strict'
_ = require('lodash')
yeoman = require('yeoman-generator')
chalk = require('chalk')
yosay = require('yosay')
module.exports = yeoman.generators.NamedBase.extend(
  prompting: ->
    done = @async()
    # Have Yeoman greet the user.
    @log yosay('Welcome to ' + chalk.cyan('Yiang - yieldifys ng') + ' generator!')
    console.log "\nModule name: "+ chalk.white @name
    console.log "\n"
    prompts = [ {
      type: 'input'
      name: 'buildTypes'
      message: """
      Compose build list from:
        (#{chalk.cyan('a')})ll
        (#{chalk.cyan('d')})irective
        (#{chalk.cyan('c')})ontroller

        default:
      """
      default: 'a'
    } ]
    @prompt prompts, (props) =>
      @props = props
      # To access props later use this.props.someOption;
      done()
      return
    return
  writing:
    app: ->
      buildTypes = @props?.buildTypes
      isAll = _.contains buildTypes, 'a'
      if isAll or _.contains buildTypes, 'd'
        @composeWith 'yiang:directive', { options: {}, args: [@name]}
      if isAll or _.contains buildTypes, 'c'
        @composeWith 'yiang:controller', { options: {}, args: [@name]}
      # @fs.copy @templatePath('_package.json'), @destinationPath('package.json')
      # @fs.copy @templatePath('_bower.json'), @destinationPath('bower.json')
      return
    projectfiles: ->
      # @fs.copy @templatePath('editorconfig'), @destinationPath('.editorconfig')
      # @fs.copy @templatePath('jshintrc'), @destinationPath('.jshintrc')
      return
  install: ->
    # @installDependencies()
    return
)

# ---
# generated by js2coffee 2.0.4